NOTIFY_INFO = 10
NOTIFY_URGENT = 20
NOTIFY_VERY_URGENT = 30
NOTIFY_WARNING = 40
NOTIFY_ERROR = 50


NOTIFY_LEVEL = {
    NOTIFY_INFO: '通知',
    NOTIFY_URGENT: '紧急',
    NOTIFY_VERY_URGENT: '非常紧急',
    NOTIFY_WARNING: '警告',
    NOTIFY_ERROR: '错误',
}